name: CI

on:
  push:
    branches-ignore:
      - 'gh-readonly-queue/**' # don't run (again) when on these special branches created during merge groups; the `on: merge_group` already triggers it.
  merge_group:

env:
  PYTHONUNBUFFERED: True
  PRE_COMMIT_HOME: ${{ github.workspace }}/.precommit_cache

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: |
            main.tex
          docker_image: texlive/texlive@sha256:62927d994f09aea455c8ea9da034af14764f9e2276a616b413545e7cec69c06b

      - name: Upload PDF file
        uses: actions/upload-artifact@v7.0.0
        with:
          name: PDF
          path: haggadah.pdf